# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'team' do
    use_frameworks!
    pod 'AFNetworking'
    pod 'SDWebImage'
    pod 'SDWebImage/GIF'
    pod 'SDWebImage/MapKit'
    pod 'SDWebImage/WebP'
    pod 'tolo'
    pod 'pop'
    pod 'Masonry'
    pod 'MBProgressHUD'
    pod 'YYModel'
    pod 'TPKeyboardAvoiding'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'DWUtilKit'
    pod 'GTSDK'
    pod 'Qiniu'
    # debug
    pod 'DWLogUnicode', :configurations => ['Debug']
    pod 'FLEX', :configurations => ['Debug']
    
end
